classDiagram
    class ProcessTemplate_ObrabotkaKandidata {
    }
    class Kandidaty {
        ФИО: Текст
        ТестированиеПройдено: Логический
        СобеседованиеПройдено: Логический
        РезультатТестирования: Число
        ПроверкаСБПройдена: Логический
        Комментарий: Текст
        Документы: ДокументыКандидатов
        Вакансия: ШтатныеЕдиницы
        <<Архивировать>>
        <<Сохранить>>
        <<Создать>>
        <<Удалить>>
    }
    class DokumentyKandidatov {
        Файл: Документ
        Тип: ТипыДокументов
        Название: Текст
        <<Архивировать>>
        <<Сохранить>>
        <<Создать>>
        <<Удалить>>
    }
    class TipyDokumentov {
        Тип: Текст
        <<Архивировать>>
        <<Сохранить>>
        <<Создать>>
        <<Удалить>>
    }
    class ShtatnyeEdinitsy {
        Подразделение: Подразделения
        КоличествоШтатныхЕдиниц: Число
        КандидатНаДолжность: Кандидаты
        Должность: Текст
        <<Архивировать>>
        <<Сохранить>>
        <<Создать>>
        <<Удалить>>
    }
    class Podrazdeleniya {
        НазваниеПодразделения: Текст
        <<Архивировать>>
        <<Сохранить>>
        <<Создать>>
        <<Удалить>>
    }
    ProcessTemplate_ObrabotkaKandidata "1" -- "*" Kandidaty
    Kandidaty "0..*" -- "1" DokumentyKandidatov
    Kandidaty "1" -- "1" ShtatnyeEdinitsy
    DokumentyKandidatov "0..*" -- "1" TipyDokumentov
    ShtatnyeEdinitsy "0..*" -- "1" Podrazdeleniya 